[package]
name = "multiformats"
description = "Implementation of the Multiformats for libp2p"
repository = "https://github.com/prataprc/multiformats"
keywords = ["multiformats", "libp2p"]
version = "0.0.1"
authors = ["prataprc <prataprc@gmail.com>"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/multiformats/"
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
unsigned-varint = "*"
multibase = "*"

[dev-dependencies]
reqwest = { version = "0.10.8", features = ["blocking"] }
parse_int = "0.4.0"
